import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

/**
 * The installer artwork is generated by `pnpm art` and committed, so nothing in
 * a release build regenerates it. That is the right trade, but it means a bad
 * regeneration — or a path typo in the bundle config — would first show up as a
 * missing sidebar in an installer somebody downloaded.
 *
 * These are the sizes NSIS and WiX require, not sizes we chose. A bitmap of the
 * wrong dimensions is not rejected; it is stretched, or cropped, or silently
 * ignored, which is exactly the kind of failure nobody notices until it ships.
 */
const TAURI_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "src-tauri");

interface Configured {
  what: string;
  at: string[];
  width: number;
  height: number;
  format: "bmp" | "png";
}

const REQUIRED: Configured[] = [
  {
    what: "NSIS sidebar",
    at: ["bundle", "windows", "nsis", "sidebarImage"],
    width: 164,
    height: 314,
    format: "bmp",
  },
  {
    what: "NSIS header",
    at: ["bundle", "windows", "nsis", "headerImage"],
    width: 150,
    height: 57,
    format: "bmp",
  },
  {
    what: "NSIS uninstaller header",
    at: ["bundle", "windows", "nsis", "uninstallerHeaderImage"],
    width: 150,
    height: 57,
    format: "bmp",
  },
  {
    what: "WiX banner",
    at: ["bundle", "windows", "wix", "bannerPath"],
    width: 493,
    height: 58,
    format: "bmp",
  },
  {
    what: "WiX dialog",
    at: ["bundle", "windows", "wix", "dialogImagePath"],
    width: 493,
    height: 312,
    format: "bmp",
  },
  {
    what: "DMG background",
    at: ["bundle", "macOS", "dmg", "background"],
    width: 660,
    height: 420,
    format: "png",
  },
];

const config = JSON.parse(readFileSync(resolve(TAURI_DIR, "tauri.conf.json"), "utf8"));

function at(path: string[]): unknown {
  return path.reduce<unknown>(
    (node, key) => (node as Record<string, unknown> | undefined)?.[key],
    config,
  );
}

function read(path: string): DataView {
  const bytes = readFileSync(resolve(TAURI_DIR, path));
  return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
}

function signature(view: DataView, length: number): number[] {
  return Array.from({ length }, (_, i) => view.getUint8(i));
}

function dimensions(view: DataView, format: "bmp" | "png"): [number, number] {
  if (format === "bmp") {
    expect(signature(view, 2)).toEqual([0x42, 0x4d]); // "BM"
    return [view.getInt32(18, true), view.getInt32(22, true)];
  }
  expect(signature(view, 8)).toEqual([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  return [view.getUint32(16, false), view.getUint32(20, false)];
}

describe.each(REQUIRED)("$what", (asset) => {
  const configured = at(asset.at);

  it("is configured in tauri.conf.json", () => {
    expect(typeof configured).toBe("string");
  });

  it(`exists and is exactly ${asset.width}×${asset.height}`, () => {
    expect(dimensions(read(configured as string), asset.format)).toEqual([
      asset.width,
      asset.height,
    ]);
  });
});

describe("NSIS bitmaps", () => {
  /** Uncompressed, 24-bit, bottom-up. RLE and 32-bit-with-alpha are where
   * installer bitmaps quietly fail to appear at all. */
  it.each([
    ["sidebarImage"],
    ["headerImage"],
    ["uninstallerHeaderImage"],
  ])("%s is an uncompressed 24-bit bottom-up BMP", (key) => {
    const view = read(at(["bundle", "windows", "nsis", key]) as string);
    expect(view.getUint16(28, true)).toBe(24);
    expect(view.getUint32(30, true)).toBe(0);
    expect(view.getInt32(22, true)).toBeGreaterThan(0);
  });
});

describe("DMG geometry", () => {
  /** The background carves a clearing for each icon. If the icons move and the
   * artwork does not, they land on top of the corona instead of in the holes
   * drawn for them — so the numbers in `render-installer-art.mts` and the ones
   * here have to stay in step. */
  it("puts both icons on the same line, inside the window", () => {
    const dmg = at(["bundle", "macOS", "dmg"]) as {
      windowSize: { width: number; height: number };
      appPosition: { x: number; y: number };
      applicationFolderPosition: { x: number; y: number };
    };

    expect(dmg.appPosition.y).toBe(dmg.applicationFolderPosition.y);
    expect(dmg.appPosition.x).toBeGreaterThan(64);
    expect(dmg.applicationFolderPosition.x).toBeLessThan(dmg.windowSize.width - 64);
    expect(dmg.appPosition.y).toBeLessThan(dmg.windowSize.height - 64);
  });
});
